# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  name: 'DaviNote'
  demands:  
  - Agent.Name -equals NOTEDAVI

variables:
  solution: '**/FullStack.API.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    
    
- task: AzureWebApp@1  
  inputs:
    azureSubscription: 'Azure for Students(455d2c50-7b5b-4f0a-ac03-05812944e317)'
    appType: 'webApp'
    appName: 'FullStackDemoBackEnd'
    package: '$(build.artifactStagingDirectory)/WebApp.zip'
    appSettings: '-dbConection "Server=tcp:dbfullstackdemo.database.windows.net,1433;Initial Catalog=dbdemo;Persist Security Info=False;User ID=davisouza;Password=Davi.O.S;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;"'
    deploymentMethod: 'auto'